version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run:
          name: Hello World
          command: echo 'Salut !'
        #    steps:
        #      - checkout
        #      - run:
        #          name: Satisfy Server Requirements
        #          command: |
        #            apt-get update \
        #            && apt-get install -y libonig-dev \
        #            && docker-php-ext-install \
        #              mbstring \
        #              pdo \
        #              pdo_sqlite
        #      - run:
        #          name: Install Dependencies
        #          command: |
        #            composer install -o
        #      -run:
        #        name: Preapre Database
        #        command: |
        #          touch ./storage/app/testing.sqlite && php ./artisan migrate --env=testing --database=sqlite_testing
        #      - run:
        #        name: Run Tests
        #        command: |
      #          php ./vendor/bin/phpunit
