version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run:
          name: Satisfy Server Requirements
          command: |
            sudo apt-get update
            sudo apt-get install -y sqlite3 libsqlite3-dev
            sudo docker-php-ext-install \
              mbstring \
              pdo \
              pdo_sqlite
      - run:
          name: Install Dependencies
          command: composer install && composer dump-autoload --optimize
      - run:
          name: Prepare Database
          command: touch database/database.sqlite && php artisan migrate --env=testing --database=sqlite
        #      - run:
        #        name: Run Tests
        #        command: |
      #          php ./vendor/bin/phpunit
